version: '3'

services:
  postgres_db:
    container_name: postgres_db
    image: "postgres:12"
    ports:
      - '5431:5432'
    expose:
      - '5431'
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: banco_digital
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/postgresql/data
  banco_digital_api:
    container_name: banco_digital_api
    build: ./
    command: ["nodemon", "index.js"]
    environment:
      PGUSER: postgres
      PGDATABASE: banco_digital
      PGPASSWORD: 1234
      PGHOST: 127.0.0.1
    ports:
      - '4000:4000'
    volumes:
      - ./:/srv/app
    restart: on-failure
    # depends_on:
    #   - postgres_db
    networks:
      - backend
networks:
  backend:
    driver: 'bridge'
volumes:
  db-data:


        